---
- hosts: "{{ dynamic_Hosts_Variable }}"
  gather_facts: False
  vars_files:
    - variables.yml
  tasks:

  - name: Ensure dotnet-aspnetcoremodule-v2 installed
    win_chocolatey:
      name: dotnet-aspnetcoremodule-v2
      state: present
      version: 15.0.21023
      source: http://internal/odata/repo

    - name: remove directory
      win_file:
        state: absent
        path: C:\inetpub\wwwroot\webapi
    
    - name: create directory
      win_file: 
        state: directory
        path: C:\inetpub\wwwroot\webapi
      # become: false

    - name: copy app.zip file
      win_copy:
        src: ../../release.zip
        dest: C:\inetpub\wwwroot\webapi
      # become: false
    
    - name: Unzip app folder
      win_unzip:
        src: C:\inetpub\wwwroot\webapi\release.zip
        dest: C:\inetpub\wwwroot\webapi

    - name: Add ACME webapplication on IIS.
      win_iis_website:
        name: webapi-core
        state: started
        port: 8081
        physical_path: C:\inetpub\wwwroot\webapi\release
  