---
- hosts: "{{ dynamic_Hosts_Variable }}"
  gather_facts: False
  vars_files:
    - variables.yml
  
  tasks:
  - name: Ensure dotnet-aspnetcoremodule-v2 installed
    win_chocolatey:
      name: dotnet-aspnetcoremodule-v2
      state: present
      version: 15.0.21023

  - name: Ensure dotnet-5.0-windowshosting installed
    win_chocolatey:
      name: dotnet-5.0-windowshosting
      state: present
      version: 5.0.3
  
  - name: Ensure dotnet-sdk installed
    win_chocolatey:
      name: dotnet-sdk
      state: present
      version: 5.0.103

  - name: Add app on IIS.
    win_iis_website:
      name: webapi-core
      state: started
      port: 8081
      physical_path: C:\inetpub\wwwroot\webapi\release
  